# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
#    container:
#      image: i386/ubuntu:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: |
          sudo apt install 2to3
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install zlib1g:i386
          sudo apt install libsnappy-dev:i386
          sudo apt install liblz4-1:i386
          wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/cibyl/cibyl-bin-linux32-21.tar.gz
          tar -zxvf cibyl-bin-linux32-21.tar.gz
          export PATH="$PATH:$HOME/runner/work/cibyl-testing/cibyl-testing/cibyl-bin-linux32-21/mips-cibyl-elf/bin"
          chmod a+x /home/runner/work/cibyl-testing/cibyl-testing/cibyl-bin-linux32-21/mips-cibyl-elf/bin/mips-cibyl-elf-gcc
          echo $PATH
          echo done.
          
      - name: Build the application
        run: |
          mv cibyl-bin-linux32-21/mips-cibyl-elf/bin/python cibyl-bin-linux32-21/mips-cibyl-elf/bin/python.old
          mkdir cibyl-bin-linux32-21/mips-cibyl-elf/bin/python
          2to3 --output-dir=cibyl-bin-linux32-21/mips-cibyl-elf/bin/python.old -W -n cibyl-bin-linux32-21/mips-cibyl-elf/bin/python
          cd cibyl-bin-linux32-21/examples/host-java/hello-world
          pwd
          dir
          sed -i '6s#.*#	/home/runner/work/cibyl-testing/cibyl-testing/cibyl-bin-linux32-21/mips-cibyl-elf/bin/mips-cibyl-elf-gcc -Os -o $@ $<#' Makefile
          sed -i '9s#.*#	/home/runner/work/cibyl-testing/cibyl-testing/cibyl-bin-linux32-21/mips-cibyl-elf/bin/cibyl-mips2java -O -d tmpclasses -DNOJ2ME program#' Makefile
          cat Makefile
          make

#          cd cibyl-bin-linux32-21/mips-cibyl-elf/bin
#          cp /home/runner/work/cibyl-testing/cibyl-testing/cibyl-bin-linux32-21/examples/host-java/hello-world/main.c main.c
#          cp /home/runner/work/cibyl-testing/cibyl-testing/cibyl-bin-linux32-21/examples/host-java/hello-world/Makefile Makefile
#          cp /home/runner/work/cibyl-testing/cibyl-testing/cibyl-bin-linux32-21/examples/host-java/hello-world/manifest.txt manifest.txt
#          pwd
#          dir
#          make
#          dir
