# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
#    container:
#      image: i386/ubuntu:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          file /usr/lib/x86_64-linux-gnu/libz.so.1.3
          file /usr/lib/x86_64-linux-gnu/libz.so.1
          file /usr/share/miniconda/lib/libz.so.1
          file /usr/share/miniconda/lib/libz.so.1.3.1
          file /usr/share/miniconda/pkgs/libzlib-1.3.1-hb25bd0a_0/lib/libz.so.1
          file /usr/share/miniconda/pkgs/libzlib-1.3.1-hb25bd0a_0/lib/libz.so.1.3.1
          file /usr/local/aws-cli/v2/2.33.28/dist/libz.so.1
          file /usr/local/julia1.12.5/lib/julia/libz.so.1
          file /usr/local/julia1.12.5/lib/julia/libz.so.1.3.1
          file /usr/local/aws-sam-cli/1.154.0/dist/_internal/libz.so.1
          wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/cibyl/cibyl-bin-linux32-21.tar.gz
          tar -zxvf cibyl-bin-linux32-21.tar.gz
          export PATH=$PATH:/home/runner/work/cibyl-testing/cibyl-testing/cibyl-bin-linux32-21/mips-cibyl-elf/bin/
          cd /home/runner/work/cibyl-testing/cibyl-testing/cibyl-bin-linux32-21/examples/host-java/hello-world/
          make
          dir
          cd /home/runner/work/cibyl-testing/cibyl-testing/cibyl-bin-linux32-21/examples/j2me/hello-world/
          make
          dir
          echo Add other actions to build,
          echo test, and deploy your project.
